ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'OWNER';
ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'PASSWORD_CHANGED';

ALTER TABLE "AdminUser"
ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT true;
